[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.64.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.64.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.64.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.64.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[redirects]
  from = "https://5e4b7708f5d7780009bf32a7--sangam-test.netlify.com/"
  to = "https://sangam-test.netlify.com/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
